name: il_env
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  flutter_markdown: ^0.7.4+1
  firebase_core: ^3.6.0
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  url_launcher: ^6.3.1
  google_generative_ai: ^0.4.6
  supabase_flutter: ^2.8.1
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700