// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB72msqXMJ9A7sDNZuDuawyEFiUqnQx0kg',
    appId: '1:638894468273:web:5d0ea1cfd8c0308ac0c690',
    messagingSenderId: '638894468273',
    projectId: 'il-env',
    authDomain: 'il-env.firebaseapp.com',
    storageBucket: 'il-env.firebasestorage.app',
    measurementId: 'G-0HX4RFTT15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBedHMnGnJlraDXyq7yQpXJQBSjz7l0VH4',
    appId: '1:638894468273:android:cf7d6a6717e362fcc0c690',
    messagingSenderId: '638894468273',
    projectId: 'il-env',
    storageBucket: 'il-env.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ji_yFHQF4F1F1kn0VvtkfItGYDOeRWY',
    appId: '1:638894468273:ios:e40f2a5d30e1a512c0c690',
    messagingSenderId: '638894468273',
    projectId: 'il-env',
    storageBucket: 'il-env.firebasestorage.app',
    iosBundleId: 'com.bysuhaib.ilEnv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ji_yFHQF4F1F1kn0VvtkfItGYDOeRWY',
    appId: '1:638894468273:ios:e40f2a5d30e1a512c0c690',
    messagingSenderId: '638894468273',
    projectId: 'il-env',
    storageBucket: 'il-env.firebasestorage.app',
    iosBundleId: 'com.bysuhaib.ilEnv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB72msqXMJ9A7sDNZuDuawyEFiUqnQx0kg',
    appId: '1:638894468273:web:1f212c0812f097ecc0c690',
    messagingSenderId: '638894468273',
    projectId: 'il-env',
    authDomain: 'il-env.firebaseapp.com',
    storageBucket: 'il-env.firebasestorage.app',
    measurementId: 'G-LYZ3J9MDZT',
  );
}
