import 'package:il_env/index.dart';

class TranslationsService extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'keyHelpText': 'What will we learn today?',
          'keyQuestionHint': 'Do you have a question regarding this section?',
          'keyStudyLessons': 'Start Studying',
          'keyUpdate': 'Update',
          'keySettings': 'Settings',
          'keySuccess': 'Success',
          'keySettingsSavedSuccessfully': 'Settings saved successfully',
          'keyError': 'Error',
          'keyCheckConnection':
              'Please check your internet connection and try again.',
          'keyApiKeyError':
              'We could not connect to the model. Make sure to add your API key correctly or switch to a different provider.',
          'keyLessonPrompt': 'Enter the lesson or article',
          'keyMainGoals': 'Main Goals',
          'keyCoreConcepts': 'Core Concepts',
          'keyImportantPoints': 'Important Points',
          'keyContentPreparation': 'Content is being prepared',
          'keyNoData': 'No data available',
          'keyLessonBasicsTitle': 'Lesson Basics',
          'keyDeepExplanation': 'Deeper Explanation',
          'keyExploreQuestions': 'Exploratory Questions',
          'keyDirectQuestion': 'Direct Question',
          'keySuccessCopied': 'Copied to clipboard',
          'keyExam': 'Exam',
          'keyLessonKeys': 'Lesson Keys',
          'keyStudyWithAI': 'Study with AI',
          'keyTestMe': 'Test Me',
          'keyFlashcards': 'Flashcards',
          'keyHomePage': 'Home Page',
          'keyPrevious': 'Previous',
          'keyNext': 'Next',
          'keySubmitExam': 'Submit Exam',
          'keyTrue': 'True',
          'keyFalse': 'False',
          'keyUploadImage': 'Upload Image',
          'keySelectImage': 'Select Image',
          'keyWriteYourAnswerHere': 'Write your answer here',
          'keyRetryExam': 'Retry Exam',
          'keyNewExam': 'New Exam',
          'keyCreateApiKey': 'Create New API Key',
          'keyInvalidCredentials': 'Invalid login credentials',
          'keyUserAlreadyRegistered': 'User already registered',
          'keyWeakPassword': 'Password should be at least 6 characters',
          'keyEmailNotConfirmed': 'Email not confirmed',
          'keyAuthError': 'Authentication Error',
          'keyUnexpectedError': 'An unexpected error occurred',
          'keyEmail': 'Email',
          'keyEnterYourEmail': 'Enter your email',
          'keyPassword': 'Password',
          'keyEnterYourPassword': 'Enter your password',
          'keySignUp': 'Sign Up',
          'keySignIn': 'Sign In',
          'keyAlreadyHaveAccount': 'Already have an account? Sign In',
          'keyDontHaveAccount': 'Don\'t have an account? Sign Up',
          'keyInviteFriend': 'Invite a Friend',
          'keyAddAppToHomeScreen':
              'Add Smart Learning Environment to your home screen!',
          'keyFasterAccessBetterExperience':
              'Faster access, better study experience.',
          'keyInstantAccess': 'Instant Access: Open the app with just one tap.',
          'keyBetterOrganization':
              'Better Organization: Keep all your study resources in one place and stored locally.',
          'keySaveData': 'Reduce internet usage and save data.',
          'keySmoothExperience': 'Smooth and enhanced user experience.',
          'keyInstallNow': 'Install App',
          'keyRemindLater': 'Remind me Later',
          'keyInstallNotSupported':
              'This browser does not support installing as an application.',
          'keyInstalling': 'Installing...',
          'keyCheckNotificationProgress':
              'Check the notification progress bar.',
          'keyPoliciesAndTerms': 'Policies and Terms',
          'keyAbout': 'About',
        },
        'ar_SA': {
          'keyHelpText': 'ماذا سنتعلم اليوم؟',
          'keyQuestionHint': 'هل لديك سؤال في هذه الجزئية؟',
          'keyStudyLessons': 'إبدأ المذاكرة',
          'keyUpdate': 'تحديث',
          'keySettings': 'الإعدادات',
          'keySuccess': 'نجاح',
          'keySettingsSavedSuccessfully': 'تم حفظ الإعدادات بنجاح',
          'keyError': 'خطأ',
          'keyCheckConnection':
              'يرجى التحقق من الاتصال بالإنترنت والمحاولة مرة أخرى.',
          'keyApiKeyError':
              'لم نتمكن من الاتصال بالنموذج. تأكد من إضافة مفتاح API الخاص بك بشكل صحيح أو التبديل لمزود مختلف.',
          'keyLessonPrompt': 'صور الدرس أو المقالة',
          'keyMainGoals': 'الأهداف الرئيسية',
          'keyCoreConcepts': 'المفاهيم الأساسية',
          'keyImportantPoints': 'النقاط المهمة',
          'keyContentPreparation': 'يتم تجهيز المحتوى',
          'keyNoData': 'لا يوجد بيانات',
          'keyLessonBasicsTitle': 'أساسيات الدرس',
          'keyDeepExplanation': 'شرح أعمق',
          'keyExploreQuestions': 'أسئلة استكشافية',
          'keyDirectQuestion': 'سؤال مباشر',
          'keySuccessCopied': 'تم النسخ إلى الحافظة',
          'keyExam': 'اختبار',
          'keyLessonKeys': 'مفاتيح الدرس',
          'keyStudyWithAI': 'ذاكر مع AI',
          'keyTestMe': 'اختبرني',
          'keyFlashcards': 'بطاقات الحفظ',
          'keyHomePage': 'الصفحة الرئيسية',
          'keyPrevious': 'السابق',
          'keyNext': 'التالي',
          'keySubmitExam': 'تقديم الاختبار',
          'keyTrue': 'صحيح',
          'keyFalse': 'خطأ',
          'keyUploadImage': 'تحميل صورة',
          'keySelectImage': 'اختر صورة',
          'keyWriteYourAnswerHere': 'اكتب إجابتك هنا',
          'keyRetryExam': 'إعادة الاختبار',
          'keyNewExam': 'اختبار جديد',
          'keyCreateApiKey': 'أنشئ مفتاح API جديد',
          'keyInvalidCredentials': 'اسم المستخدم أو كلمة المرور غير صحيحة',
          'keyUserAlreadyRegistered': 'هذا المستخدم مسجل بالفعل',
          'keyWeakPassword': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
          'keyEmailNotConfirmed':
              'البريد الإلكتروني لم يتم تأكيده، يرجى التحقق من بريدك الوارد',
          'keyAuthError': 'خطأ في المصادقة',
          'keyUnexpectedError': 'حدث خطأ غير متوقع',
          'keyEmail': 'البريد الإلكتروني',
          'keyEnterYourEmail': 'أدخل بريدك الإلكتروني',
          'keyPassword': 'كلمة المرور',
          'keyEnterYourPassword': 'أدخل كلمة المرور',
          'keySignUp': 'إنشاء حساب',
          'keySignIn': 'تسجيل الدخول',
          'keyAlreadyHaveAccount': 'هل لديك حساب بالفعل؟ تسجيل الدخول',
          'keyDontHaveAccount': 'ليس لديك حساب؟ إنشاء حساب',
          'keyInviteFriend': 'دعوة صديق',
          'keyAddAppToHomeScreen':
              'أضف بيئة التعليم الذكية كتطبيق إلى شاشتك الرئيسية!',
          'keyFasterAccessBetterExperience': 'وصول أسرع، تجربة أفضل للدراسة.',
          'keyInstantAccess':
              'وصول فوري: سيمكنك من فتح التطبيق بنقرة واحدة فقط.',
          'keyBetterOrganization':
              'تنظيم أفضل: حافظ على جميع مواردك الدراسية في مكان واحد ومخزنة محليا.',
          'keySaveData': 'تقليل استهلاك الانترنت و توفير البيانات',
          'keySmoothExperience': 'تجربة استخدام سلسة ومحسّنة.',
          'keyInstallNow': 'بتثبيت التطبيق',
          'keyRemindLater': 'تذكير لاحقًا',
          'keyInstallNotSupported': 'هذا المتصفح لا يدعم التثبيت كتطبيق.',
          'keyInstalling': 'جاري التثبيت...',
          'keyCheckNotificationProgress': 'شاهد شريط التقدم في الإشعارات',
          'keyPoliciesAndTerms': 'السياسات والشروط',
          'keyAbout': 'حول',
        },
      };
}

enum TranslationKey {
  keyHelpText,
  keyQuestionHint,
  keyStudyLessons,
  keyUpdate,
  keySettings,
  keySuccess,
  keySettingsSavedSuccessfully,
  keyError,
  keyCheckConnection,
  keyApiKeyError,
  keyLessonPrompt,
  keyMainGoals,
  keyCoreConcepts,
  keyImportantPoints,
  keyContentPreparation,
  keyNoData,
  keyLessonBasicsTitle,
  keyDeepExplanation,
  keyExploreQuestions,
  keyDirectQuestion,
  keySuccessCopied,
  keyExam,
  keyLessonKeys,
  keyStudyWithAI,
  keyTestMe,
  keyFlashcards,
  keyHomePage,
  keyPrevious,
  keyNext,
  keySubmitExam,
  keyWriteYourAnswerHere,
  keyRetryExam,
  keyNewExam,
  keyTrue,
  keyFalse,
  keyUploadImage,
  keySelectImage,
  keyCreateApiKey,
  keyInvalidCredentials,
  keyUserAlreadyRegistered,
  keyWeakPassword,
  keyEmailNotConfirmed,
  keyAuthError,
  keyUnexpectedError,
  keyEmail,
  keyEnterYourEmail,
  keyPassword,
  keyEnterYourPassword,
  keySignUp,
  keySignIn,
  keyAlreadyHaveAccount,
  keyDontHaveAccount,
  keyInviteFriend,
  keyAddAppToHomeScreen,
  keyFasterAccessBetterExperience,
  keyInstantAccess,
  keyBetterOrganization,
  keySaveData,
  keySmoothExperience,
  keyInstallNow,
  keyRemindLater,
  keyInstallNotSupported,
  keyInstalling,
  keyCheckNotificationProgress,
  keyPoliciesAndTerms,
  keyAbout,
}

String translateKeyTr(TranslationKey key) {
  return key.name.tr;
}

void toggleLanguageFun() async {
  if (Get.locale?.languageCode == 'en') {
    await storage.write(key: 'language', value: 'ar');
    Get.updateLocale(Locale('ar', 'SA'));
  } else {
    await storage.write(key: 'language', value: 'en');
    Get.updateLocale(Locale('en', 'US'));
  }
}
