import 'package:get/get.dart';

class TranslationsService extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'keyHelpText': 'What will we learn today?',
          'keyQuestionHint': 'Do you have a question regarding this section?',
          'keyStudyLessons': 'Start Studying',
          'keyUpdateSettings': 'Update Settings',
          'keySettings': 'Settings',
          'keySuccess': 'Success',
          'keySettingsSavedSuccessfully': 'Settings saved successfully',
          'keyError': 'Error',
          'keyCheckConnection':
              'Please check your internet connection and try again.',
          'keyApiKeyError':
              'We could not connect to the model. Make sure to add your API key correctly or switch to a different provider.',
          'keyLessonPrompt': 'Enter the lesson or article',
          'keyMainGoals': 'Main Goals',
          'keyCoreConcepts': 'Core Concepts',
          'keyImportantPoints': 'Important Points',
          'keyContentPreparation': 'Content is being prepared',
          'keyNoData': 'No data available',
          'keyLessonBasicsTitle': 'Lesson Basics',
          'keyDeepExplanation': 'Deeper Explanation',
          'keyExploreQuestions': 'Exploratory Questions',
          'keyDirectQuestion': 'Direct Question',
          'keySuccessCopied': 'Copied to clipboard',
          'keyExam': 'Exam',
          'keyLessonKeys': 'Lesson Keys',
          'keyStudyWithAI': 'Study with AI',
          'keyTestMe': 'Test Me',
          'keyFlashcards': 'Flashcards',
          'keyHomePage': 'Home Page',
          'keyPrevious': 'Previous',
          'keyNext': 'Next',
          'keySubmitExam': 'Submit Exam',
          'keyTrue': 'True',
          'keyFalse': 'False',          
          'keyUploadImage': 'Upload Image',
          'keySelectImage': 'Select Image',
          'keyWriteYourAnswerHere': 'Write your answer here',
          'keyRetryExam': 'Retry Exam',
          'keyNewExam': 'New Exam',
          'keyCreateApiKey': 'Create Your API Key',
          'keyUpdateRequired': 'Update Required',
          'keyUpdateAvailable': 'New Update Available',
          'keyUpdate': 'Update',
          'keyLater': 'Later',
          'keyGoogleSignInFailed': 'Google sign in failed',
          'keyGoogleAuthFailed': 'Google auth failed',
          'keyFirebaseSignInFailed': 'Firebase sign in failed',
          'keyUnknownError': 'Unknown error',
          'keyFailedToGetUser': 'Failed to get user data',
          'keyInvitationCodeCannotBeEmpty': 'Invitation code cannot be empty',
          'keyInvitationCodeCannotBeYours': 'Invitation code cannot be yours',
          'keyInvitationCodeNotFound': 'Invitation code not found',
          'keyYouHaveBeenInvited': 'You have been invited',
          'keyInvitationCodeSuccess': 'Invitation code success',
        },
        'ar_SA': {
          'keyHelpText': 'ماذا سنتعلم اليوم؟',
          'keyQuestionHint': 'هل لديك سؤال في هذه الجزئية؟',
          'keyStudyLessons': 'إبدأ المذاكرة',
          'keyUpdateSettings': 'تحديث الإعدادات',
          'keySettings': 'الإعدادات',
          'keySuccess': 'نجاح',
          'keySettingsSavedSuccessfully': 'تم حفظ الإعدادات بنجاح',
          'keyError': 'خطأ',
          'keyCheckConnection':
              'يرجى التحقق من الاتصال بالإنترنت والمحاولة مرة أخرى.',
          'keyApiKeyError':
              'لم نتمكن من الاتصال بالنموذج. تأكد من إضافة مفتاح API الخاص بك بشكل صحيح أو التبديل لمزود مختلف.',

          'keyLessonPrompt': 'ضع الدرس أو المقالة',
          'keyMainGoals': 'الأهداف الرئيسية',
          'keyCoreConcepts': 'المفاهيم الأساسية',
          'keyImportantPoints': 'النقاط المهمة',
          'keyContentPreparation': 'يتم تجهيز المحتوى',
          'keyNoData': 'لا يوجد بيانات',
          'keyLessonBasicsTitle': 'أساسيات الدرس',
          'keyDeepExplanation': 'شرح أعمق',
          'keyExploreQuestions': 'أسئلة استكشافية',
          'keyDirectQuestion': 'سؤال مباشر',
          'keySuccessCopied': 'تم النسخ إلى الحافظة',
          'keyExam': 'اختبار',
          'keyLessonKeys': 'مفاتيح الدرس',
          'keyStudyWithAI': 'ذاكر مع AI',
          'keyTestMe': 'اختبرني',
          'keyFlashcards': 'بطاقات الحفظ',
          'keyHomePage': 'الصفحة الرئيسية',
          'keyPrevious': 'السابق',
          'keyNext': 'التالي',
          'keySubmitExam': 'تقديم الاختبار',
          'keyTrue': 'صحيح',
          'keyFalse': 'خطأ',          
          'keyUploadImage': 'تحميل صورة',
          'keySelectImage': 'اختر صورة',
          'keyWriteYourAnswerHere': 'اكتب إجابتك هنا',
          'keyRetryExam': 'إعادة الاختبار',
          'keyNewExam': 'اختبار جديد',
          'keyCreateApiKey': 'أنشئ مفتاح API الخاص بك',
          'keyUpdateRequired': 'تحديث ضروري',
          'keyUpdateAvailable': 'متوفر تحديث جديد',
          'keyUpdate': 'تحديث',
          'keyLater': 'لاحقا',
          'keyGoogleSignInFailed': 'فشل تسجيل الدخول باستخدام جوجل',
          'keyGoogleAuthFailed': 'فشل الحصول على مصادقة جوجل',
          'keyFirebaseSignInFailed': 'فشل تسجيل الدخول باستخدام Firebase',
          'keyUnknownError': 'حدث خطأ غير متوقع',
          'keyFailedToGetUser': 'فشل الحصول على بيانات المستخدم',
          'keyInvitationCodeCannotBeEmpty': 'كود الدعوة لا يمكن أن يكون فارغًا',
          'keyInvitationCodeCannotBeYours': 'كود الدعوة لا يمكن أن يكون خاصًا بك',
          'keyInvitationCodeNotFound': 'كود الدعوة غير موجود',
          'keyYouHaveBeenInvited': 'لقد تمت دعوتك بالفعل',
          'keyInvitationCodeSuccess': 'تمت إضافة كود الدعوة بنجاح',
        },
      };
}

enum TranslationKey {
  keyHelpText,
  keyQuestionHint,
  keyStudyLessons,
  keyUpdateSettings,
  keySettings,
  keySuccess,
  keySettingsSavedSuccessfully,
  keyError,
  keyCheckConnection,
  keyApiKeyError,
  keyLessonPrompt,
  keyMainGoals,
  keyCoreConcepts,
  keyImportantPoints,
  keyContentPreparation,
  keyNoData,
  keyLessonBasicsTitle,
  keyDeepExplanation,
  keyExploreQuestions,
  keyDirectQuestion,
  keySuccessCopied,
  keyExam,
  keyLessonKeys,
  keyStudyWithAI,
  keyTestMe,
  keyFlashcards,
  keyHomePage,
  keyPrevious,
  keyNext,
  keySubmitExam,
  keyWriteYourAnswerHere,
  keyRetryExam,
  keyNewExam,
  keyTrue,
  keyFalse,
  keyUploadImage,
  keySelectImage,
  keyCreateApiKey,
  keyUpdateRequired,
  keyUpdateAvailable,
  keyUpdate,
  keyLater,
  keyGoogleSignInFailed,
  keyGoogleAuthFailed,
  keyFirebaseSignInFailed,
  keyUnknownError,
  keyFailedToGetUser,
  keyInvitationCodeCannotBeEmpty,
  keyInvitationCodeCannotBeYours,
  keyInvitationCodeNotFound,
  keyYouHaveBeenInvited,
  keyInvitationCodeSuccess,
}

String translateKeyTr(TranslationKey key) {
  return key.name.tr;
}
